"""initial schema

Revision ID: bde5a891d3b4
Revises: 
Create Date: 2026-06-17 10:26:37.694552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bde5a891d3b4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aluno',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ultimo_acesso', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('prerequisito',
    sa.Column('topico_id', sa.UUID(), nullable=False),
    sa.Column('requer_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('topico_id', 'requer_id')
    )
    op.create_table('topico',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('exercicio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topico_id', sa.UUID(), nullable=False),
    sa.Column('enunciado', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('nivel_bloom', sa.Integer(), nullable=False),
    sa.Column('gabarito', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('casos_de_teste', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['topico_id'], ['topico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progresso_aluno',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aluno_id', sa.UUID(), nullable=False),
    sa.Column('topico_id', sa.UUID(), nullable=False),
    sa.Column('proficiencia', sa.Float(), nullable=False),
    sa.Column('tentativas', sa.Integer(), nullable=False),
    sa.Column('acertos', sa.Integer(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('proxima_revisao', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ),
    sa.ForeignKeyConstraint(['topico_id'], ['topico.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aluno_id', 'topico_id')
    )
    op.create_table('sessao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aluno_id', sa.UUID(), nullable=False),
    sa.Column('exercicio_id', sa.UUID(), nullable=False),
    sa.Column('codigo_submetido', sa.Text(), nullable=True),
    sa.Column('correto', sa.Boolean(), nullable=False),
    sa.Column('dicas_usadas', sa.Integer(), nullable=False),
    sa.Column('delta_proficiencia', sa.Float(), nullable=False),
    sa.Column('realizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ),
    sa.ForeignKeyConstraint(['exercicio_id'], ['exercicio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback_ia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sessao_id', sa.UUID(), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('nivel_dica', sa.String(length=20), nullable=False),
    sa.Column('tokens_usados', sa.Integer(), nullable=False),
    sa.Column('gerado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sessao_id'], ['sessao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sessao_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback_ia')
    op.drop_table('sessao')
    op.drop_table('progresso_aluno')
    op.drop_table('exercicio')
    op.drop_table('topico')
    op.drop_table('prerequisito')
    op.drop_table('aluno')
    # ### end Alembic commands ###
